# Prometheus configuration for Entropic Storage Engine
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'entropic-monitor'
    environment: 'development'

# Alertmanager configuration (optional)
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
          # - 'alertmanager:9093'

# Load rules once and periodically evaluate them
rule_files:
  - "alerts/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'

  # Entropic Storage Engine metrics
  - job_name: 'entropic'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['entropic:8080']
        labels:
          service: 'entropic'
          component: 'api'
    scrape_timeout: 10s
    scrape_interval: 15s

  # Node Exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'node-exporter'
          host: 'docker-host'

  # PostgreSQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
        labels:
          service: 'postgres'
          database: 'entropic'

  # Typesense metrics (if available)
  - job_name: 'typesense'
    metrics_path: '/metrics.json'
    static_configs:
      - targets: ['typesense:8108']
        labels:
          service: 'typesense'
          component: 'search'

  # Jaeger metrics
  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:14269']
        labels:
          service: 'jaeger'
          component: 'tracing'

  # Loki metrics
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
        labels:
          service: 'loki'
          component: 'logging'

  # Grafana metrics
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
        labels:
          service: 'grafana'
          component: 'visualization'