package: generated
output: ../internal/generated/openapi.gen.go
generate:
  - types
  - server
  - spec
  - skip-prune
client-package: client
client-output: ../pkg/client/client.gen.go
client-generate:
  - types
  - client
additional-imports:
  - package: github.com/google/uuid
    alias: ""
  - package: time
    alias: ""
import-mapping:
  uuid.UUID: github.com/google/uuid
strict-server: true
embed-spec: true
